version: '3.7'

volumes:
  postgres_data:
      driver: local

services:
  postgres:
      image: postgres
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 1
  
  keycloak:
    image: quay.io/keycloak/keycloak:13.0.1
    container_name: 'keycloak'
    ports:
      - '8080:8080'
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: postgres
      DB_PASSWORD: 1
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_URL: jdbc:postgresql://host.docker.internal:5432/camunda
    depends_on:
      - postgres
